spring.application.name=library_manager
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
# Swagger UI accesed by: http://localhost:8080/swagger-ui.html